config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root'diyou#home'
  get 'diyou/about'
  get 'diyou/term'
  get 'diyou/privacy'

  get 'recipes/readyfor'
  get 'recipes/new'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  resources :relationships, only: [:create, :destroy]

  resources :users, except: [:index]

  resources :recipes do
    get 'page/:page', :action => :index, :on => :collection
    resources :ingredients
    resources :steps
  end

  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :ingredients
  has_many :steps

  # Validation
  validates :recipe_name, :category, presence: true

  # Uploader
  mount_uploader :main_image, MainImageUploader

  accepts_nested_attributes_for :ingredients, allow_destroy: true # この行を追記
  accepts_nested_attributes_for :steps, allow_destroy: true # この行を追記

  #relationships
  has_many :favoring_relationships, class_name:  "Relationship",
                                    foreign_key: "favorited_id",
                                    dependent:   :destroy
  has_many :favoriter_users, through: :favoring_relationships, source: :favoriter

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :recipe_owner, only: [:edit, :update, :destroy]
  before_action :category_set, only: [:new, :index, :edit]
  before_action :recipe_find, only: [:show, :edit, :update]

  def index
    @recipes = Recipe.order(created_at: :desc)

    #検索
    @q = Recipe.page(params[:page]).search(params[:q])
    @searchedRecipes = @q.result(distinct: true)

    @title = "レシピ一覧"


  end

  def readyfor
    @title = "はじめよう！"
  end

  def new
    @recipe = Recipe.new
    2.times{ @recipe.ingredients.build }
    @recipe.steps.build
    @title = "新規レシピ作成"


  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = "新規プロジェクトを作成しました"
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def show

    @recipe_title = @recipe.recipe_name

  end

  def edit

    @recipe.ingredients.build

  end

  def update

    if @recipe.update(edit_recipe_params)
      flash[:success] = "プロジェクト内容が更新されました"
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = current_user.recipes.find_by(id: params[:id])
    return redirect_to root_url if @recipe.nil?
    @recipe.destroy
    flash[:success] = "プロジェクトは削除されました"
    redirect_to recipes_path
  end


# 編集中
private

  def category_set
    @categories = ["アクセサリー","ガーデン","水回り","椅子","机", "その他"]
  end

  def recipe_find
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params
      .require(:recipe).permit(:recipe_name, :category, :main_image, :level, :time, :cost, :youtube_url, ingredients_attributes: [:id, :material_name, :qty, :ing_image], steps_attributes: [:id, :step_image, :description])
  end

  def edit_recipe_params
    params.require(:recipe).permit(:recipe_name, :category, :main_image, :level, :time, :cost, :youtube_url,
      ingredients_attributes: [:id, :material_name, :qty, :ing_image], steps_attributes: [:id, :step_image, :description])
  end

  #recipe のオーナーかどうか判断
  def recipe_owner
    @recipe = Recipe.find(params[:id])
    unless @recipe.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this project'
      redirect_to recipes_path
    end
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="field">
    <%= f.nested_fields_for :ingredients do |ingredients_form| %>
      <%= ingredients_form.label :material_name, "材料/道具名" %>
      <%= ingredients_form.text_field :material_name %><br />
      <%= ingredients_form.label :qty, "量・個数" %>
      <%= ingredients_form.text_field :qty %><br />
      <%= ingredients_form.label :ing_image, "写真" %>
      <%= ingredients_form.text_field :ing_image %><br />
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_list.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% recipes.order("created_at desc").each do |recipe| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">
            <% if recipe.main_image.present? %>
              <%= link_to image_tag(recipe.main_image.url , alt: recipe.recipe_name), recipe %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: recipe.recipe_name), recipe %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= recipe.recipe_name %>
        </div>
        <div class="action clearfix">
          <% if recipe.category == "アクセサリー" %>
            <%= link_to "#{recipe.category}", recipe , class: "btn-have btn btn-warning btn-sm", style: "background-color: green; border-color: green;" %>

          <% elsif recipe.category == "ガーデン" %>
            <%= link_to "#{recipe.category}", recipe , class: "btn-have btn btn-warning btn-sm", style: "background-color: orange; border-color: orange;" %>

          <% elsif recipe.category == "水回り" %>
            <%= link_to "#{recipe.category}", recipe , class: "btn-have btn btn-warning btn-sm", style: "background-color: #4B0082; border-color: #4B0082;" %>

          <% elsif recipe.category == "椅子" %>
            <%= link_to "#{recipe.category}", recipe , class: "btn-have btn btn-warning btn-sm", style: "background-color: blue; border-color: blue;" %>

          <% elsif recipe.category == "机" %>
            <%= link_to "#{recipe.category}", recipe , class: "btn-have btn btn-warning btn-sm", style: "background-color: pink; border-color: pink;" %>

           <% else %>
            <%= link_to "#{recipe.category}", recipe , class: "btn-have btn btn-warning btn-sm", style: "background-color: red; border-color: red;" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_list_users.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% recipes.order("created_at desc").each do |recipe| %>
      <div class="item-box-mini">
        <div class="image">
          <div class="img-wrap">
            <% if recipe.main_image.present? %>
              <%= link_to image_tag(recipe.main_image.url , alt: recipe.recipe_name), recipe %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: recipe.recipe_name), recipe %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= recipe.recipe_name %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<% content_for :head do %>
  <meta name="title" content="新規レシピ作成">
  <meta name="description" content="新しいレシピを作成しよう">
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3 edit-project">
  <h3 style="text-align: center;">レシピを作成する</h3>
    <%= simple_form_for(@recipe) do |f| %>
    <!-- error messages -->
    <%= f.error_notification %>
      <%= f.input :category, label: 'カテゴリー', as: :select, collection: @categories, include_blank: '選択してください', class: "form-control" %></br>
      <%= f.label :recipe_name, "レシピ名" %>
      <%= f.text_field :recipe_name,error: 'レシピ名は必須です。', :placeholder => "(例) 新感覚デニムを一からつくる！", class: "form-control" %><br/>
      <%= f.input :main_image, label: "メイン画像", as: :image_preview, input_html: { preview_version: :thumb }, class: "form-control" %><br/>
      <%= f.label :youtube_url, "Youtube動画 URL" %>
      <%= f.text_field :youtube_url, as: :url, label: '',:placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx", class: "form-control" %></br>

  <!-- 材料・道具追加のテーブル -->
  <table class="table table-striped table-bordered table-hover">
    <%= f.label :ingredients, "材料・道具を追加" %>
          <tbody>
            <tr>
               <th>材料/道具名</th>
               <th>量・個数</th>
               <th>写真</th>
               <th>Action</th>
            </tr>
            <%= f.nested_fields_for :ingredients, wrapper_tag: :tr do |q| %>
                <td><%= q.text_field   :material_name,     class: 'form-control', :placeholder => "例) ドライバー" %></td>
                <td><%= q.text_field :qty, class: 'form-control', :placeholder => "例) 1個" %></td>
                <td><%= q.file_field   :ing_image,     class: 'form-control' %></td>
                <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
            <% end %>
        </tbody>
    </table>
      <%= f.add_nested_fields_link :ingredients, '材料追加', class: 'btn btn-primary', role: 'button' %></br></br>

    <!-- 各ステップ追加のテーブル -->
    <table class="table table-striped table-bordered table-hover">
      <%= f.label :steps, "ステップを追加" %>
          <tbody>
            <tr>
               <th>イメージ</th>
               <th>説明</th>
               <th>Action</th>
            </tr>
            <%= f.nested_fields_for :steps, wrapper_tag: :tr do |q| %>
                <td><%= q.file_field   :step_image,     class: 'form-control' %></td>
                <td><%= q.text_field   :description,     class: 'form-control' %></td>
                <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
            <% end %>
        </tbody>
    </table>
      <%= f.add_nested_fields_link :steps, 'ステップ追加', class: 'btn btn-primary', role: 'button' %></br></br>
      <%= f.submit "レシピを投稿する！", class: "btn btn-large btn-primary form-control" %>
    <% end %>

  </div>
</div>

app/views/recipes/index.html.erb
<% content_for :head do %>
  <meta name="title" content="<%= @title %>">
  <meta name="description" content="レシピの一覧ページです。">
<% end %>

<div class="container">
  <!-- 検索フィールド -->
   <div class="search">
     <div class="search__icons">
        <span class="search__item search__item1">
          <%= search_form_for @q, html: { id: 'search__item_select', class: 'search__item_select' } do |f| %><br/>
          <div class="search__item_select">
          <!-- カテゴリーで検索 -->
            <%= f.select :category_cont, options_for_select(@categories), {include_blank: 'カテゴリーから検索'}, {class: "search__item_select"} %>
            <%= f.submit "検索する", class: "btn btn-sm btn-info" %>
            <% end %>
          </div>
        </span>

        <span class="search__item form__search">
          <%= search_form_for @q, html: { id: 'search__item_select', class: 'form__search' } do |f| %>
          <!-- start 特定の文字列で始まる商品名で検索 -->
            <%= f.search_field :recipe_name_cont, id:'keyword',class: "form-control form-control-inline", placeholder: "好きな言葉をここに" %>
            <%= f.submit "検索する", id:'search',class: "btn btn-sm btn-info" %>
          <% end %>
        </span>
      </div>
   </div>
</div><!-- container -->

<% if @q == nil %>
<div class="container index-project">
    <div class="container">
      <%= render 'recipes/list' , recipes: @recipes %>
      <%= paginate @recipes, class: 'pagenation' %>
    </div>
  <% else %>
    <div class="container">
      <%= render 'recipes/list' , recipes: @searchedRecipes %>
      <div class="pagenation"><%= paginate @searchedRecipes %>
    <% end %>
    </div>
    </div>
</div>

app/views/recipes/new.html.erb
<% content_for :head do %>
  <meta name="title" content="新規レシピ作成">
  <meta name="description" content="新しいレシピを作成しよう">
<% end %>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3 edit-project">
  <h3 style="text-align: center;">レシピを作成する</h3>
    <%= simple_form_for @recipe, wrapper: "horizontal_form", :html => { :class => 'form-horizontal' } do |f| %>
    <!-- error messages -->
    <%= f.error_notification %>
      <%= f.input :category, label: 'カテゴリー', as: :select, collection: ["アクセサリー","ガーデン","水回り","椅子","机", "その他"], include_blank: '選択してください', class: "form-control" %></br>
      <%= f.label :recipe_name, "レシピ名" %>
      <%= f.text_field :recipe_name,error: 'レシピ名は必須です。', :placeholder => "(例) 新感覚デニムを一からつくる！", class: "form-control" %><br/>
      <%= f.label :time, "所要時間" %>
      <%= f.text_field :time,error: '時間は必須です。', :placeholder => "20", class: "form-control" %><br/>
      <%= f.input :main_image, label: "メイン画像", as: :image_preview, input_html: { preview_version: :thumb }, class: "form-control", onchange:"readURL(this);" %><br/>
      <%= f.hidden_field :main_image_cache %>
      <div id="img_prev">
        <%= image_tag("") %></br>
      </div>
      <%= f.label :youtube_url, "Youtube動画 URL" %>
      <%= f.text_field :youtube_url, as: :url, label: '',:placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx", class: "form-control" %></br>

  <!-- 材料・道具追加のテーブル -->
  <table class="table table-striped table-bordered table-hover">
    <%= f.label :ingredients, "材料・道具を追加" %>
          <tbody>
            <tr>
               <th>材料/道具名</th>
               <th>量・個数</th>
               <th>写真</th>
               <th>Action</th>
            </tr>
            <%= f.nested_fields_for :ingredients, wrapper_tag: :tr do |q| %>
                <td><%= q.text_field   :material_name,     class: 'form-control', :placeholder => "例) ドライバー" %></td>
                <td><%= q.text_field :qty, class: 'form-control', :placeholder => "例) 1個" %></td>
                <td><%= q.file_field   :ing_image,     class: 'form-control' %></td>
                <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
            <% end %>
        </tbody>
    </table>
      <%= f.add_nested_fields_link :ingredients, '材料追加', class: 'btn btn-primary', role: 'button' %></br></br>

    <!-- 各ステップ追加のテーブル -->
    <table class="table table-striped table-bordered table-hover">
      <%= f.label :steps, "ステップを追加" %>
          <tbody>
            <tr>
               <th>イメージ</th>
               <th>説明</th>
               <th>Action</th>
            </tr>
            <%= f.nested_fields_for :steps, wrapper_tag: :tr do |q| %>
                <td><%= q.file_field   :step_image,     class: 'form-control' %></td>
                <td><%= q.text_field   :description,     class: 'form-control' %></td>
                <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
            <% end %>
        </tbody>
    </table>
      <%= f.add_nested_fields_link :steps, 'ステップ追加', class: 'btn btn-primary', role: 'button' %></br></br>
      <%= f.submit "レシピを投稿する！", class: "btn btn-large btn-primary form-control" %>
    <% end %>

  </div>
</div>

<script>
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            $('#img_prev')
              .attr('src', e.target.result)
              .width(150)
              .height(200);
          };

          reader.readAsDataURL(input.files[0]);
        }
      }
    </script>

app/views/recipes/readyfor.html.erb
<% content_for :head do %>
  <meta name="title" content="<%= @title %>">
  <meta name="description" content="プロジェクトをはじめよう！">
<% end %>

<div id="ready-for-jumbotron">
    <div class="container">
      <h1 style="text-align: center;">DIYou</h1>
      <p style="text-align: center;">ものづくり</p>
      <h3>How to write your own recipe?</h3><br/>
      <h2>⬇︎</h2>
    </div><!-- /.container -->
</div><!-- /.jumbotron -->

<div id="readyfor-contents" class="container">
  <h2>使い方はかんたん。<br/>
  レシピを作成してスタートするだけ。</h2>
  <div class="row">
    <div class="col-md-4">
      <h4><span class="step">1</span> レシピを作成</h4>
    </div>
    <div class="col-md-4">
      <h4><span class="step">2</span> レシピを作成して、みんなに共有する。</h4>
    </div>
    <div class="col-md-4">
      <h4><span class="step">3</span> ものづくりをたのしむ！</h4>
    </div>
  </div>
  <% if user_signed_in?  %>
    <h5><%= link_to "レシピを作成する", recipes_new_path, class: "btn btn-large btn-info" %></h5>
  <% else %>
    <h5><%= link_to "まずは新規会員登録する", new_user_registration_path, class: "post btn btn-large btn-info" %></h5>
  <% end %>
</div>
<div id="about" class="container">

</div>
<div id="about-zadankai">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <!-- 写真か何かを入れる -->
        <%= image_tag '/images/shutterstock_347801048.jpg' %>
      </div>
      <div class="col-md-6">
        <h2>DIYouとは</h2>
        <p>こんなものを創りたい。こんなアレンジをしたら楽しそう！。<br/>
        そういったあなたの心の中にある思いを形にして、それをみんなで共有できる「ものづくりの場」をつくりたい。<br/>
        そんな思いから、この「DIYou」はスタートしました。<br/>
        気軽にあなたが創った作品のレシピをシェアして、ものづくりを楽しもう！<br/>
        </p>
      </div>

    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@recipe.recipe_name %>">
  <meta name="description" content="「<%= @recipe.recipe_name %>」に関する情報です">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-2 project-user-profile">
      <% if @recipe.user != nil %>
      <h4><%= @recipe.user.username %></h4>
        <!-- image -->
        <% if @recipe.user.remote_avatar != nil %>
          <%= link_to image_tag(@recipe.user.remote_avatar , alt: @recipe.user.username), user_path(@recipe.user) %>
        <% elsif @recipe.user.avatar.url != nil %>
          <%= link_to image_tag(@recipe.user.avatar.url , alt: @recipe.user.username), user_path(@recipe.user) %>
        <% else %>
          <%= link_to image_tag("/images/user.jpg" , alt: "No Image"), user_path(@recipe.user) %>
        <% end %>
      <% end %>

      <div class="recipe_edit">
        <% if current_user == @recipe.user && current_user != nil %>
            <%= link_to "レシピの編集", edit_recipe_path(@recipe), class: "btn btn-large btn-default" %>
        <% end %>
      </div>
    </div>

    <!-- Main Contents -->
    <div class= "col-sm-7">
      <div class="title">
        <h2 class="recipe_name"><%= @recipe.recipe_name %></h2>
        <%= render 'users/favorite_form' %>
      </div></br>
        <%= image_tag(@recipe.main_image) %></br></br>
      <!-- facebook いいね -->
      <div class="fb-like" data-href="<%= "http://#{request.host+request.fullpath}" %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
      <!-- 材料表示(Ingredients) -->

      <table class="table table-hover">
      <h3>材料/道具</h3>
        <thead>
            <tr>
               <th>材料/道具名</th>
               <th>量・個数</th>
               <th>写真</th>
            </tr>
        </thead>
          <% @recipe.ingredients.order("created_at asc").each do |ingredient| %>
        <tbody>
            <td><%= ingredient.material_name %></td>
            <td><%= ingredient.qty %></td>
            <td>
              <!-- 材料の写真表示 -->
              <% if ingredient.ing_image.url != nil %>
               <%= image_tag(ingredient.ing_image , alt: "image") %>
              <% else%>
                <%= image_tag("/images/no_images.png" , alt: "no image") %>
              <% end %>
            </td>
          <% end %>
        </tbody>
      </table>

      <div><!-- 手順表示(Steps) -->
        <table class="table table-hover">
        <h3>手順</h3>
        <thead>
          <tr>
             <th>手順写真</th>
             <th>詳細</th>
          </tr>
        </thead>
            <% @recipe.steps.order("created_at asc").each do |step| %>
        <tbody>
            <td>
              <!-- 手順の写真表示 -->
              <% if step.step_image.url != nil %>
                <p><%= image_tag(step.step_image , alt: "image") %></p>
              <% else %>
                <p><%= image_tag("/images/no_images.png" , alt: "no image") %></p>
              <% end %>
            </td>
            <td><%= step.description %></td>
          <% end %>
        </tbody>
      </table
    </div>

  </div>
</div>